// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/categories/category.proto

/*
Package categories is a generated protocol buffer package.

It is generated from these files:
	proto/categories/category.proto

It has these top-level messages:
	UpsertCategoriesReq
	UpsertCategoriesRsp
	CategoriesReq
	CategoriesRsp
	Category
*/
package categories

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/timestamp"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type UpsertCategoriesReq struct {
	Categories []*Category `protobuf:"bytes,1,rep,name=categories" json:"categories,omitempty"`
}

func (m *UpsertCategoriesReq) Reset()                    { *m = UpsertCategoriesReq{} }
func (m *UpsertCategoriesReq) String() string            { return proto.CompactTextString(m) }
func (*UpsertCategoriesReq) ProtoMessage()               {}
func (*UpsertCategoriesReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *UpsertCategoriesReq) GetCategories() []*Category {
	if m != nil {
		return m.Categories
	}
	return nil
}

type UpsertCategoriesRsp struct {
	Matched    int64       `protobuf:"varint,1,opt,name=matched" json:"matched,omitempty"`
	Modified   int64       `protobuf:"varint,2,opt,name=modified" json:"modified,omitempty"`
	Categories []*Category `protobuf:"bytes,3,rep,name=categories" json:"categories,omitempty"`
}

func (m *UpsertCategoriesRsp) Reset()                    { *m = UpsertCategoriesRsp{} }
func (m *UpsertCategoriesRsp) String() string            { return proto.CompactTextString(m) }
func (*UpsertCategoriesRsp) ProtoMessage()               {}
func (*UpsertCategoriesRsp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *UpsertCategoriesRsp) GetMatched() int64 {
	if m != nil {
		return m.Matched
	}
	return 0
}

func (m *UpsertCategoriesRsp) GetModified() int64 {
	if m != nil {
		return m.Modified
	}
	return 0
}

func (m *UpsertCategoriesRsp) GetCategories() []*Category {
	if m != nil {
		return m.Categories
	}
	return nil
}

type CategoriesReq struct {
}

func (m *CategoriesReq) Reset()                    { *m = CategoriesReq{} }
func (m *CategoriesReq) String() string            { return proto.CompactTextString(m) }
func (*CategoriesReq) ProtoMessage()               {}
func (*CategoriesReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type CategoriesRsp struct {
	Categories []*Category `protobuf:"bytes,1,rep,name=categories" json:"categories,omitempty"`
}

func (m *CategoriesRsp) Reset()                    { *m = CategoriesRsp{} }
func (m *CategoriesRsp) String() string            { return proto.CompactTextString(m) }
func (*CategoriesRsp) ProtoMessage()               {}
func (*CategoriesRsp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *CategoriesRsp) GetCategories() []*Category {
	if m != nil {
		return m.Categories
	}
	return nil
}

type Category struct {
	// @inject_tag: bson:"_id" valid:"uuidv4~Category ID must be a valid UUIDv4" conform:"trim"
	ID string `protobuf:"bytes,1,opt,name=ID" json:"ID,omitempty" bson:"_id" valid:"uuidv4~Category ID must be a valid UUIDv4" conform:"trim"`
	// @inject_tag: bson:"name" valid:"required~Category name is required" conform:"trim"
	Name string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty" bson:"name" valid:"required~Category name is required" conform:"trim"`
	// @inject_tag: bson:"slug" valid:"required~Category slug is required" conform:"trim,slug"
	Slug string `protobuf:"bytes,3,opt,name=slug" json:"slug,omitempty" bson:"slug" valid:"required~Category slug is required" conform:"trim,slug"`
	// @inject_tag: bson:"url" valid:"required~Category url is required, url~Category url must be a valid URL" conform:"trim"
	Url string `protobuf:"bytes,4,opt,name=url" json:"url,omitempty" bson:"url" valid:"required~Category url is required, url~Category url must be a valid URL" conform:"trim"`
	// @inject_tag: bson:"display_order"
	DisplayOrder int64 `protobuf:"varint,5,opt,name=display_order,json=displayOrder" json:"display_order,omitempty" bson:"display_order"`
	// @inject_tag: bson:"hidden"
	Hidden bool `protobuf:"varint,6,opt,name=hidden" json:"hidden,omitempty" bson:"hidden"`
	// @inject_tag: bson:"created_at"
	CreatedAt *google_protobuf.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt" json:"created_at,omitempty" bson:"created_at"`
	// @inject_tag: bson:"updated_at"
	UpdatedAt *google_protobuf.Timestamp `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt" json:"updated_at,omitempty" bson:"updated_at"`
}

func (m *Category) Reset()                    { *m = Category{} }
func (m *Category) String() string            { return proto.CompactTextString(m) }
func (*Category) ProtoMessage()               {}
func (*Category) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *Category) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *Category) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Category) GetSlug() string {
	if m != nil {
		return m.Slug
	}
	return ""
}

func (m *Category) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *Category) GetDisplayOrder() int64 {
	if m != nil {
		return m.DisplayOrder
	}
	return 0
}

func (m *Category) GetHidden() bool {
	if m != nil {
		return m.Hidden
	}
	return false
}

func (m *Category) GetCreatedAt() *google_protobuf.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *Category) GetUpdatedAt() *google_protobuf.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

func init() {
	proto.RegisterType((*UpsertCategoriesReq)(nil), "go.micro.srv.products.UpsertCategoriesReq")
	proto.RegisterType((*UpsertCategoriesRsp)(nil), "go.micro.srv.products.UpsertCategoriesRsp")
	proto.RegisterType((*CategoriesReq)(nil), "go.micro.srv.products.CategoriesReq")
	proto.RegisterType((*CategoriesRsp)(nil), "go.micro.srv.products.CategoriesRsp")
	proto.RegisterType((*Category)(nil), "go.micro.srv.products.Category")
}

func init() { proto.RegisterFile("proto/categories/category.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 398 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x52, 0x4f, 0xef, 0xd2, 0x40,
	0x10, 0x4d, 0xdb, 0x9f, 0x50, 0x06, 0x50, 0x5c, 0xa3, 0xd9, 0xf4, 0x42, 0x83, 0x1e, 0x1a, 0x0f,
	0x4b, 0x82, 0x27, 0x4f, 0x06, 0xe5, 0xc2, 0x49, 0x53, 0xff, 0xc4, 0x78, 0x21, 0xa5, 0xbb, 0x94,
	0x35, 0x2d, 0xbb, 0xee, 0x6e, 0x49, 0xf8, 0x04, 0x5e, 0xfc, 0x82, 0x7e, 0x1b, 0xd3, 0xa5, 0xe5,
	0x5f, 0x50, 0x31, 0xde, 0x66, 0xde, 0xbc, 0x37, 0xb3, 0x33, 0xfb, 0x60, 0x28, 0x95, 0x30, 0x62,
	0x9c, 0x26, 0x86, 0x65, 0x42, 0x71, 0xa6, 0x9b, 0x70, 0x47, 0x6c, 0x05, 0x3d, 0xce, 0x04, 0x29,
	0x78, 0xaa, 0x04, 0xd1, 0x6a, 0x5b, 0x61, 0xb4, 0x4c, 0x8d, 0x0e, 0x86, 0x99, 0x10, 0x59, 0xce,
	0xc6, 0x96, 0xb4, 0x2c, 0x57, 0x63, 0xc3, 0x0b, 0xa6, 0x4d, 0x52, 0xc8, 0xbd, 0x6e, 0xf4, 0x09,
	0x1e, 0x7d, 0x94, 0x9a, 0x29, 0xf3, 0xe6, 0xd0, 0x3a, 0x66, 0xdf, 0xd0, 0x2b, 0x80, 0xe3, 0x2c,
	0xec, 0x84, 0x5e, 0xd4, 0x9d, 0x0c, 0xc9, 0xd5, 0x19, 0xa4, 0x56, 0xee, 0xe2, 0x13, 0xc9, 0xe8,
	0x87, 0x73, 0xa5, 0xb1, 0x96, 0x08, 0x43, 0xbb, 0x48, 0x4c, 0xba, 0x66, 0x14, 0x3b, 0xa1, 0x13,
	0x79, 0x71, 0x93, 0xa2, 0x00, 0xfc, 0x42, 0x50, 0xbe, 0xe2, 0x8c, 0x62, 0xd7, 0x96, 0x0e, 0xf9,
	0xc5, 0x73, 0xbc, 0x7f, 0x7f, 0xce, 0x03, 0xe8, 0x9f, 0x2d, 0x38, 0x7a, 0x77, 0x06, 0x68, 0xf9,
	0xff, 0x1b, 0x7f, 0x77, 0xc1, 0x6f, 0x0a, 0xe8, 0x3e, 0xb8, 0xf3, 0x99, 0xdd, 0xb0, 0x13, 0xbb,
	0xf3, 0x19, 0x42, 0x70, 0xb7, 0x49, 0x0a, 0x66, 0x17, 0xeb, 0xc4, 0x36, 0xae, 0x30, 0x9d, 0x97,
	0x19, 0xf6, 0xf6, 0x58, 0x15, 0xa3, 0x01, 0x78, 0xa5, 0xca, 0xf1, 0x9d, 0x85, 0xaa, 0x10, 0x3d,
	0x85, 0x3e, 0xe5, 0x5a, 0xe6, 0xc9, 0x6e, 0x21, 0x14, 0x65, 0x0a, 0xdf, 0xb3, 0xb7, 0xe9, 0xd5,
	0xe0, 0xdb, 0x0a, 0x43, 0x4f, 0xa0, 0xb5, 0xe6, 0x94, 0xb2, 0x0d, 0x6e, 0x85, 0x4e, 0xe4, 0xc7,
	0x75, 0x86, 0x5e, 0x02, 0xa4, 0x8a, 0x25, 0x86, 0xd1, 0x45, 0x62, 0x70, 0x3b, 0x74, 0xa2, 0xee,
	0x24, 0x20, 0x7b, 0x4f, 0x90, 0xc6, 0x13, 0xe4, 0x43, 0xe3, 0x89, 0xb8, 0x53, 0xb3, 0xa7, 0xa6,
	0x92, 0x96, 0x92, 0x36, 0x52, 0xff, 0xef, 0xd2, 0x9a, 0x3d, 0x35, 0x93, 0x9f, 0x0e, 0x3c, 0x3c,
	0x1e, 0xf7, 0x3d, 0x53, 0x5b, 0x9e, 0x32, 0xf4, 0x15, 0x06, 0x97, 0x86, 0x40, 0xcf, 0x7f, 0x73,
	0xe0, 0x2b, 0x96, 0x0c, 0x6e, 0xe6, 0x6a, 0x89, 0x3e, 0x03, 0x9c, 0x4c, 0x79, 0xf6, 0xe7, 0x6f,
	0xac, 0xfb, 0xdf, 0xc0, 0xd2, 0xf2, 0x75, 0xef, 0xcb, 0xc9, 0x9f, 0x2f, 0x5b, 0xf6, 0x10, 0x2f,
	0x7e, 0x05, 0x00, 0x00, 0xff, 0xff, 0x39, 0x0f, 0x7b, 0x22, 0x9f, 0x03, 0x00, 0x00,
}
