// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/categories/category.proto

/*
Package categories is a generated protocol buffer package.

It is generated from these files:
	proto/categories/category.proto

It has these top-level messages:
	UpsertCategoriesReq
	UpsertCategoriesRsp
	Category
*/
package categories

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type UpsertCategoriesReq struct {
	Categories []*Category `protobuf:"bytes,1,rep,name=categories" json:"categories,omitempty"`
}

func (m *UpsertCategoriesReq) Reset()                    { *m = UpsertCategoriesReq{} }
func (m *UpsertCategoriesReq) String() string            { return proto.CompactTextString(m) }
func (*UpsertCategoriesReq) ProtoMessage()               {}
func (*UpsertCategoriesReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *UpsertCategoriesReq) GetCategories() []*Category {
	if m != nil {
		return m.Categories
	}
	return nil
}

type UpsertCategoriesRsp struct {
	Categories []*Category `protobuf:"bytes,1,rep,name=categories" json:"categories,omitempty"`
}

func (m *UpsertCategoriesRsp) Reset()                    { *m = UpsertCategoriesRsp{} }
func (m *UpsertCategoriesRsp) String() string            { return proto.CompactTextString(m) }
func (*UpsertCategoriesRsp) ProtoMessage()               {}
func (*UpsertCategoriesRsp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *UpsertCategoriesRsp) GetCategories() []*Category {
	if m != nil {
		return m.Categories
	}
	return nil
}

type Category struct {
	// @inject_tag: valid:"uuidv4~Category ID must be a valid UUIDv4" conform:"trim"
	ID string `protobuf:"bytes,1,opt,name=ID" json:"ID,omitempty" valid:"uuidv4~Category ID must be a valid UUIDv4" conform:"trim"`
	// @inject_tag: valid:"required~Category name is required" conform:"trim"
	Name string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty" valid:"required~Category name is required" conform:"trim"`
	// @inject_tag: valid:"required~Category slug is required" conform:"trim,slug"
	Slug string `protobuf:"bytes,3,opt,name=slug" json:"slug,omitempty" valid:"required~Category slug is required" conform:"trim,slug"`
	// @inject_tag: valid:"required~Category url is required, url~Category url must be a valid URL" conform:"trim"
	Url          string `protobuf:"bytes,4,opt,name=url" json:"url,omitempty" valid:"required~Category url is required, url~Category url must be a valid URL" conform:"trim"`
	DisplayOrder int64  `protobuf:"varint,5,opt,name=display_order,json=displayOrder" json:"display_order,omitempty"`
	CreatedAt    int64  `protobuf:"varint,6,opt,name=created_at,json=createdAt" json:"created_at,omitempty"`
	UpdatedAt    int64  `protobuf:"varint,7,opt,name=updated_at,json=updatedAt" json:"updated_at,omitempty"`
}

func (m *Category) Reset()                    { *m = Category{} }
func (m *Category) String() string            { return proto.CompactTextString(m) }
func (*Category) ProtoMessage()               {}
func (*Category) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Category) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *Category) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Category) GetSlug() string {
	if m != nil {
		return m.Slug
	}
	return ""
}

func (m *Category) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *Category) GetDisplayOrder() int64 {
	if m != nil {
		return m.DisplayOrder
	}
	return 0
}

func (m *Category) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *Category) GetUpdatedAt() int64 {
	if m != nil {
		return m.UpdatedAt
	}
	return 0
}

func init() {
	proto.RegisterType((*UpsertCategoriesReq)(nil), "go.micro.srv.products.UpsertCategoriesReq")
	proto.RegisterType((*UpsertCategoriesRsp)(nil), "go.micro.srv.products.UpsertCategoriesRsp")
	proto.RegisterType((*Category)(nil), "go.micro.srv.products.Category")
}

func init() { proto.RegisterFile("proto/categories/category.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 282 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x92, 0x41, 0x4b, 0xc3, 0x40,
	0x14, 0x84, 0x49, 0x52, 0xab, 0x7d, 0x56, 0xa9, 0x2b, 0xc2, 0x22, 0x48, 0x83, 0x5e, 0x82, 0x87,
	0x08, 0xf5, 0x07, 0x48, 0xb5, 0x97, 0x9e, 0x84, 0x88, 0x1e, 0xbc, 0x94, 0x98, 0x7d, 0x84, 0x48,
	0xea, 0xae, 0x6f, 0x37, 0x85, 0x9c, 0xfc, 0x59, 0xfe, 0x3d, 0xd9, 0x6d, 0x62, 0x8b, 0x44, 0x10,
	0xbc, 0x0d, 0xdf, 0xbc, 0x99, 0xc3, 0xec, 0xc2, 0x58, 0x91, 0x34, 0xf2, 0x2a, 0x4b, 0x0d, 0xe6,
	0x92, 0x0a, 0xd4, 0xad, 0xac, 0x63, 0xe7, 0xb0, 0x93, 0x5c, 0xc6, 0xcb, 0x22, 0x23, 0x19, 0x6b,
	0x5a, 0x59, 0x26, 0xaa, 0xcc, 0xe8, 0xf3, 0x27, 0x38, 0x7e, 0x54, 0x1a, 0xc9, 0xdc, 0x7d, 0x27,
	0x13, 0x7c, 0x67, 0x37, 0x00, 0x9b, 0x2a, 0xee, 0x85, 0x41, 0xb4, 0x3f, 0x19, 0xc7, 0x9d, 0x15,
	0x71, 0x93, 0xac, 0x93, 0xad, 0x48, 0x67, 0xaf, 0x56, 0xff, 0xef, 0xfd, 0xf4, 0x60, 0xaf, 0x35,
	0xd8, 0x21, 0xf8, 0xf3, 0x19, 0xf7, 0x42, 0x2f, 0x1a, 0x24, 0xfe, 0x7c, 0xc6, 0x18, 0xf4, 0xde,
	0xd2, 0x25, 0x72, 0xdf, 0x11, 0xa7, 0x2d, 0xd3, 0x65, 0x95, 0xf3, 0x60, 0xcd, 0xac, 0x66, 0x23,
	0x08, 0x2a, 0x2a, 0x79, 0xcf, 0x21, 0x2b, 0xd9, 0x05, 0x1c, 0x88, 0x42, 0xab, 0x32, 0xad, 0x17,
	0x92, 0x04, 0x12, 0xdf, 0x09, 0xbd, 0x28, 0x48, 0x86, 0x0d, 0xbc, 0xb7, 0x8c, 0x9d, 0x01, 0x64,
	0x84, 0xa9, 0x41, 0xb1, 0x48, 0x0d, 0xef, 0xbb, 0x8b, 0x41, 0x43, 0xa6, 0xc6, 0xda, 0x95, 0x12,
	0xad, 0xbd, 0xbb, 0xb6, 0x1b, 0x32, 0x35, 0x93, 0x0f, 0x38, 0xda, 0x6c, 0xf1, 0x80, 0xb4, 0x2a,
	0x32, 0x64, 0xaf, 0x30, 0xfa, 0x39, 0x13, 0xbb, 0xfc, 0x65, 0x8f, 0x8e, 0x77, 0x3a, 0xfd, 0xf3,
	0xad, 0x56, 0xb7, 0xc3, 0xe7, 0xad, 0x21, 0x5f, 0xfa, 0xee, 0x5b, 0x5c, 0x7f, 0x05, 0x00, 0x00,
	0xff, 0xff, 0x0b, 0xcf, 0xc7, 0x2b, 0x39, 0x02, 0x00, 0x00,
}
