// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/suppliers/supplier.proto

/*
Package suppliers is a generated protocol buffer package.

It is generated from these files:
	proto/suppliers/supplier.proto

It has these top-level messages:
	UpsertSuppliersReq
	UpsertSuppliersRsp
	Supplier
	SuppliersReq
	SuppliersRsp
*/
package suppliers

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type UpsertSuppliersReq struct {
	Suppliers []*Supplier `protobuf:"bytes,1,rep,name=suppliers" json:"suppliers,omitempty"`
}

func (m *UpsertSuppliersReq) Reset()                    { *m = UpsertSuppliersReq{} }
func (m *UpsertSuppliersReq) String() string            { return proto.CompactTextString(m) }
func (*UpsertSuppliersReq) ProtoMessage()               {}
func (*UpsertSuppliersReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *UpsertSuppliersReq) GetSuppliers() []*Supplier {
	if m != nil {
		return m.Suppliers
	}
	return nil
}

type UpsertSuppliersRsp struct {
	Suppliers []*Supplier `protobuf:"bytes,1,rep,name=suppliers" json:"suppliers,omitempty"`
}

func (m *UpsertSuppliersRsp) Reset()                    { *m = UpsertSuppliersRsp{} }
func (m *UpsertSuppliersRsp) String() string            { return proto.CompactTextString(m) }
func (*UpsertSuppliersRsp) ProtoMessage()               {}
func (*UpsertSuppliersRsp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *UpsertSuppliersRsp) GetSuppliers() []*Supplier {
	if m != nil {
		return m.Suppliers
	}
	return nil
}

type Supplier struct {
	// @inject_tag: valid:"uuidv4~suppliers ID must be a valid UUIDv4" conform:"trim"
	ID string `protobuf:"bytes,1,opt,name=ID" json:"ID,omitempty" valid:"uuidv4~suppliers ID must be a valid UUIDv4" conform:"trim"`
	// @inject_tag: valid:"required~Supplier name is required" conform:"trim"
	Name string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty" valid:"required~Supplier name is required" conform:"trim"`
	// @inject_tag: valid:"required~Supplier slug is required" conform:"trim,slug"
	Slug string `protobuf:"bytes,3,opt,name=slug" json:"slug,omitempty" valid:"required~Supplier slug is required" conform:"trim,slug"`
	// @inject_tag: valid:"url~Supplier logo must be a valid URL" conform:"trim"
	LogoUrl string `protobuf:"bytes,4,opt,name=logo_url,json=logoUrl" json:"logo_url,omitempty" valid:"url~Supplier logo must be a valid URL" conform:"trim"`
	// @inject_tag: valid:"required, url~Supplier home page must be a valid URL" conform:"trim"
	HomePageUrl string `protobuf:"bytes,5,opt,name=home_page_url,json=homePageUrl" json:"home_page_url,omitempty" valid:"required, url~Supplier home page must be a valid URL" conform:"trim"`
	// @inject_tag: conform:"trim"
	Currency     string `protobuf:"bytes,6,opt,name=currency" json:"currency,omitempty" conform:"trim"`
	DisplayOrder int64  `protobuf:"varint,7,opt,name=display_order,json=displayOrder" json:"display_order,omitempty"`
	CreatedAt    int64  `protobuf:"varint,8,opt,name=created_at,json=createdAt" json:"created_at,omitempty"`
	UpdatedAt    int64  `protobuf:"varint,9,opt,name=updated_at,json=updatedAt" json:"updated_at,omitempty"`
}

func (m *Supplier) Reset()                    { *m = Supplier{} }
func (m *Supplier) String() string            { return proto.CompactTextString(m) }
func (*Supplier) ProtoMessage()               {}
func (*Supplier) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Supplier) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *Supplier) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Supplier) GetSlug() string {
	if m != nil {
		return m.Slug
	}
	return ""
}

func (m *Supplier) GetLogoUrl() string {
	if m != nil {
		return m.LogoUrl
	}
	return ""
}

func (m *Supplier) GetHomePageUrl() string {
	if m != nil {
		return m.HomePageUrl
	}
	return ""
}

func (m *Supplier) GetCurrency() string {
	if m != nil {
		return m.Currency
	}
	return ""
}

func (m *Supplier) GetDisplayOrder() int64 {
	if m != nil {
		return m.DisplayOrder
	}
	return 0
}

func (m *Supplier) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *Supplier) GetUpdatedAt() int64 {
	if m != nil {
		return m.UpdatedAt
	}
	return 0
}

type SuppliersReq struct {
}

func (m *SuppliersReq) Reset()                    { *m = SuppliersReq{} }
func (m *SuppliersReq) String() string            { return proto.CompactTextString(m) }
func (*SuppliersReq) ProtoMessage()               {}
func (*SuppliersReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type SuppliersRsp struct {
	Suppliers []*Supplier `protobuf:"bytes,1,rep,name=suppliers" json:"suppliers,omitempty"`
}

func (m *SuppliersRsp) Reset()                    { *m = SuppliersRsp{} }
func (m *SuppliersRsp) String() string            { return proto.CompactTextString(m) }
func (*SuppliersRsp) ProtoMessage()               {}
func (*SuppliersRsp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *SuppliersRsp) GetSuppliers() []*Supplier {
	if m != nil {
		return m.Suppliers
	}
	return nil
}

func init() {
	proto.RegisterType((*UpsertSuppliersReq)(nil), "go.micro.srv.products.UpsertSuppliersReq")
	proto.RegisterType((*UpsertSuppliersRsp)(nil), "go.micro.srv.products.UpsertSuppliersRsp")
	proto.RegisterType((*Supplier)(nil), "go.micro.srv.products.Supplier")
	proto.RegisterType((*SuppliersReq)(nil), "go.micro.srv.products.SuppliersReq")
	proto.RegisterType((*SuppliersRsp)(nil), "go.micro.srv.products.SuppliersRsp")
}

func init() { proto.RegisterFile("proto/suppliers/supplier.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 349 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x93, 0x4d, 0x6b, 0xfa, 0x40,
	0x10, 0xc6, 0x49, 0xf4, 0xaf, 0xc9, 0xf8, 0xf2, 0x2f, 0x0b, 0x85, 0xad, 0xd0, 0x56, 0xe2, 0xc5,
	0x5e, 0x52, 0xb0, 0xe7, 0x1e, 0x2c, 0x5e, 0x3c, 0x94, 0x96, 0x88, 0x97, 0x5e, 0x42, 0x9a, 0x2c,
	0x69, 0x20, 0xba, 0xdb, 0xd9, 0x8d, 0xe0, 0xad, 0x9f, 0xb1, 0x9f, 0xa8, 0xec, 0x6a, 0xa2, 0xb4,
	0x16, 0x0b, 0xde, 0x66, 0x7e, 0xcf, 0x33, 0x4f, 0x5e, 0x66, 0x17, 0xae, 0x04, 0x72, 0xc5, 0x6f,
	0x65, 0x21, 0x44, 0x9e, 0x31, 0x94, 0x55, 0xe5, 0x1b, 0x81, 0x9c, 0xa7, 0xdc, 0x5f, 0x64, 0x31,
	0x72, 0x5f, 0xe2, 0x4a, 0xb3, 0xa4, 0x88, 0x95, 0xf4, 0x66, 0x40, 0xe6, 0x42, 0x32, 0x54, 0xb3,
	0x72, 0x30, 0x60, 0xef, 0xe4, 0x1e, 0xdc, 0x2a, 0x88, 0x5a, 0xfd, 0xda, 0xb0, 0x35, 0xba, 0xf6,
	0x0f, 0x06, 0xf8, 0xe5, 0x5c, 0xb0, 0x9b, 0x38, 0x14, 0x2a, 0xc5, 0xa9, 0xa1, 0x1f, 0x36, 0x38,
	0x25, 0x27, 0x5d, 0xb0, 0xa7, 0x13, 0x6a, 0xf5, 0xad, 0xa1, 0x1b, 0xd8, 0xd3, 0x09, 0x21, 0x50,
	0x5f, 0x46, 0x0b, 0x46, 0x6d, 0x43, 0x4c, 0xad, 0x99, 0xcc, 0x8b, 0x94, 0xd6, 0x36, 0x4c, 0xd7,
	0xe4, 0x02, 0x9c, 0x9c, 0xa7, 0x3c, 0x2c, 0x30, 0xa7, 0x75, 0xc3, 0x9b, 0xba, 0x9f, 0x63, 0x4e,
	0x3c, 0xe8, 0xbc, 0xf1, 0x05, 0x0b, 0x45, 0x94, 0x32, 0xa3, 0xff, 0x33, 0x7a, 0x4b, 0xc3, 0xe7,
	0x28, 0x65, 0xda, 0xd3, 0x03, 0x27, 0x2e, 0x10, 0xd9, 0x32, 0x5e, 0xd3, 0x86, 0x91, 0xab, 0x9e,
	0x0c, 0xa0, 0x93, 0x64, 0x52, 0xe4, 0xd1, 0x3a, 0xe4, 0x98, 0x30, 0xa4, 0xcd, 0xbe, 0x35, 0xac,
	0x05, 0xed, 0x2d, 0x7c, 0xd2, 0x8c, 0x5c, 0x02, 0xc4, 0xc8, 0x22, 0xc5, 0x92, 0x30, 0x52, 0xd4,
	0x31, 0x0e, 0x77, 0x4b, 0xc6, 0x4a, 0xcb, 0x85, 0x48, 0x4a, 0xd9, 0xdd, 0xc8, 0x5b, 0x32, 0x56,
	0x5e, 0x17, 0xda, 0xfb, 0x6b, 0xf2, 0x1e, 0xf7, 0xfb, 0x93, 0xff, 0xf0, 0xe8, 0xd3, 0x82, 0xb3,
	0x2a, 0x6f, 0xc6, 0x70, 0x95, 0xc5, 0x8c, 0xa4, 0xf0, 0xff, 0xdb, 0x2e, 0xc9, 0xcd, 0x2f, 0x99,
	0x3f, 0x0f, 0x52, 0xef, 0xaf, 0x56, 0x29, 0xc8, 0x1c, 0xdc, 0xdd, 0x23, 0x06, 0x47, 0x5e, 0xdb,
	0x84, 0x1f, 0x37, 0x49, 0xf1, 0xd0, 0x7a, 0xd9, 0x7d, 0xe1, 0x6b, 0xc3, 0xdc, 0x85, 0xbb, 0xaf,
	0x00, 0x00, 0x00, 0xff, 0xff, 0xfe, 0x02, 0x1b, 0x55, 0x2d, 0x03, 0x00, 0x00,
}
