// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/products/product.proto

/*
Package products is a generated protocol buffer package.

It is generated from these files:
	proto/products/product.proto

It has these top-level messages:
	UpsertProductsReq
	UpsertProductsRsp
	Product
*/
package products

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type UpsertProductsReq struct {
	Products []*Product `protobuf:"bytes,1,rep,name=products" json:"products,omitempty"`
}

func (m *UpsertProductsReq) Reset()                    { *m = UpsertProductsReq{} }
func (m *UpsertProductsReq) String() string            { return proto.CompactTextString(m) }
func (*UpsertProductsReq) ProtoMessage()               {}
func (*UpsertProductsReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *UpsertProductsReq) GetProducts() []*Product {
	if m != nil {
		return m.Products
	}
	return nil
}

type UpsertProductsRsp struct {
	Products []*Product `protobuf:"bytes,1,rep,name=products" json:"products,omitempty"`
}

func (m *UpsertProductsRsp) Reset()                    { *m = UpsertProductsRsp{} }
func (m *UpsertProductsRsp) String() string            { return proto.CompactTextString(m) }
func (*UpsertProductsRsp) ProtoMessage()               {}
func (*UpsertProductsRsp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *UpsertProductsRsp) GetProducts() []*Product {
	if m != nil {
		return m.Products
	}
	return nil
}

type Product struct {
	// @inject_tag: valid:"uuidv4~Product ID must be a valid UUIDv4" conform:"trim"
	ID string `protobuf:"bytes,1,opt,name=ID" json:"ID,omitempty" valid:"uuidv4~Product ID must be a valid UUIDv4" conform:"trim"`
	// @inject_tag: valid:"required~Product name is required" conform:"trim"
	Name string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty" valid:"required~Product name is required" conform:"trim"`
	// @inject_tag: valid:"required~Product slug is required" conform:"trim,slug"
	Slug string `protobuf:"bytes,3,opt,name=slug" json:"slug,omitempty" valid:"required~Product slug is required" conform:"trim,slug"`
	// @inject_tag: valid:"required~Product price is required"
	Price float32 `protobuf:"fixed32,4,opt,name=price" json:"price,omitempty" valid:"required~Product price is required"`
	// @inject_tag: valid:"required~Product currency is required"
	Currency string `protobuf:"bytes,5,opt,name=currency" json:"currency,omitempty" valid:"required~Product currency is required"`
	// @inject_tag: valid:"url~Product image must be a valid URL format"
	ImageUrl string `protobuf:"bytes,6,opt,name=image_url,json=imageUrl" json:"image_url,omitempty" valid:"url~Product image must be a valid URL format"`
	// @inject_tag: valid:"required~Product categories url is required,url~Product category url must be a valid URL format"
	CategoryUrl string `protobuf:"bytes,7,opt,name=category_url,json=categoryUrl" json:"category_url,omitempty" valid:"required~Product categories url is required,url~Product category url must be a valid URL format"`
	// @inject_tag: valid:"url~Product url must be a valid URL format"
	Url       string  `protobuf:"bytes,8,opt,name=url" json:"url,omitempty" valid:"url~Product url must be a valid URL format"`
	Rating    float32 `protobuf:"fixed32,9,opt,name=rating" json:"rating,omitempty"`
	Brand     string  `protobuf:"bytes,10,opt,name=brand" json:"brand,omitempty"`
	CreatedAt int64   `protobuf:"varint,11,opt,name=created_at,json=createdAt" json:"created_at,omitempty"`
	UpdatedAt int64   `protobuf:"varint,12,opt,name=updated_at,json=updatedAt" json:"updated_at,omitempty"`
}

func (m *Product) Reset()                    { *m = Product{} }
func (m *Product) String() string            { return proto.CompactTextString(m) }
func (*Product) ProtoMessage()               {}
func (*Product) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Product) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *Product) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Product) GetSlug() string {
	if m != nil {
		return m.Slug
	}
	return ""
}

func (m *Product) GetPrice() float32 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *Product) GetCurrency() string {
	if m != nil {
		return m.Currency
	}
	return ""
}

func (m *Product) GetImageUrl() string {
	if m != nil {
		return m.ImageUrl
	}
	return ""
}

func (m *Product) GetCategoryUrl() string {
	if m != nil {
		return m.CategoryUrl
	}
	return ""
}

func (m *Product) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *Product) GetRating() float32 {
	if m != nil {
		return m.Rating
	}
	return 0
}

func (m *Product) GetBrand() string {
	if m != nil {
		return m.Brand
	}
	return ""
}

func (m *Product) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *Product) GetUpdatedAt() int64 {
	if m != nil {
		return m.UpdatedAt
	}
	return 0
}

func init() {
	proto.RegisterType((*UpsertProductsReq)(nil), "go.micro.srv.products.UpsertProductsReq")
	proto.RegisterType((*UpsertProductsRsp)(nil), "go.micro.srv.products.UpsertProductsRsp")
	proto.RegisterType((*Product)(nil), "go.micro.srv.products.Product")
}

func init() { proto.RegisterFile("proto/products/product.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 333 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x92, 0x4d, 0x4b, 0xf3, 0x40,
	0x10, 0xc7, 0x49, 0xd2, 0x97, 0x64, 0x5a, 0xfa, 0x3c, 0x2e, 0x2a, 0x4b, 0x7d, 0x21, 0x7a, 0xca,
	0x29, 0x42, 0xbd, 0x79, 0xab, 0xf4, 0xd2, 0x93, 0x12, 0xe9, 0xc5, 0x4b, 0xd9, 0x6e, 0x96, 0x10,
	0x68, 0x92, 0x75, 0xb2, 0xa9, 0xf4, 0x63, 0xf9, 0x0d, 0x65, 0x37, 0xd9, 0x82, 0xf8, 0x82, 0xe0,
	0x6d, 0xe6, 0xf7, 0xfb, 0xef, 0xb2, 0xc9, 0x0c, 0x9c, 0x4b, 0xac, 0x54, 0x75, 0x23, 0xb1, 0x4a,
	0x1b, 0xae, 0x6a, 0x5b, 0xc4, 0x06, 0x93, 0x93, 0xac, 0x8a, 0x8b, 0x9c, 0x63, 0x15, 0xd7, 0xb8,
	0x8b, 0x6d, 0xe8, 0xfa, 0x01, 0x8e, 0x56, 0xb2, 0x16, 0xa8, 0x1e, 0x3b, 0x92, 0x88, 0x17, 0x72,
	0x07, 0xbe, 0x0d, 0x50, 0x27, 0xf4, 0xa2, 0xd1, 0xec, 0x32, 0xfe, 0xf2, 0x78, 0xdc, 0x9d, 0x4a,
	0xfc, 0x1f, 0x2e, 0xac, 0xe5, 0x9f, 0x2e, 0x7c, 0x73, 0x61, 0xd8, 0x51, 0x32, 0x01, 0x77, 0xb9,
	0xa0, 0x4e, 0xe8, 0x44, 0x41, 0xe2, 0x2e, 0x17, 0x84, 0x40, 0xaf, 0x64, 0x85, 0xa0, 0xae, 0x21,
	0xa6, 0xd6, 0xac, 0xde, 0x36, 0x19, 0xf5, 0x5a, 0xa6, 0x6b, 0x72, 0x0c, 0x7d, 0x89, 0x39, 0x17,
	0xb4, 0x17, 0x3a, 0x91, 0x9b, 0xb4, 0x0d, 0x99, 0x82, 0xcf, 0x1b, 0x44, 0x51, 0xf2, 0x3d, 0xed,
	0x9b, 0xf4, 0xa1, 0x27, 0x67, 0x10, 0xe4, 0x05, 0xcb, 0xc4, 0xba, 0xc1, 0x2d, 0x1d, 0xb4, 0xd2,
	0x80, 0x15, 0x6e, 0xc9, 0x15, 0x8c, 0x39, 0x53, 0x22, 0xab, 0x70, 0x6f, 0xfc, 0xd0, 0xf8, 0x91,
	0x65, 0x3a, 0xf2, 0x1f, 0x3c, 0x6d, 0x7c, 0x63, 0x74, 0x49, 0x4e, 0x61, 0x80, 0x4c, 0xe5, 0x65,
	0x46, 0x03, 0xf3, 0x88, 0xae, 0xd3, 0x6f, 0xdb, 0x20, 0x2b, 0x53, 0x0a, 0x26, 0xdb, 0x36, 0xe4,
	0x02, 0x80, 0xa3, 0x60, 0x4a, 0xa4, 0x6b, 0xa6, 0xe8, 0x28, 0x74, 0x22, 0x2f, 0x09, 0x3a, 0x32,
	0x57, 0x5a, 0x37, 0x32, 0xb5, 0x7a, 0xdc, 0xea, 0x8e, 0xcc, 0xd5, 0xec, 0x15, 0xfe, 0xd9, 0xdf,
	0xff, 0x24, 0x70, 0xa7, 0x3f, 0x36, 0x85, 0xc9, 0xc7, 0xb9, 0x90, 0xe8, 0x9b, 0x11, 0x7c, 0xda,
	0x87, 0xe9, 0x2f, 0x93, 0xb5, 0xbc, 0x87, 0xe7, 0xc3, 0xe0, 0x36, 0x03, 0xb3, 0x78, 0xb7, 0xef,
	0x01, 0x00, 0x00, 0xff, 0xff, 0xbb, 0xe0, 0x1c, 0x71, 0x98, 0x02, 0x00, 0x00,
}
